name: flutter_signaturepad
description: The Flutter Signature Pad widget allows you to capture smooth and more realistic signatures through drawn gestures and save it as an image.
version: 22.1.35
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  workspace_core:
    git:
      url: https://github.com/K1yoshiSho/workspace_flutter_core.git
      ref: main

flutter:
